import "./globals.css";
import Header from "./components/root/header/header";
import Footer from "./components/root/footer/footer";
import { Montserrat } from 'next/font/google'; // Montserrat fontunu ekle
import Link from "./components/root/link/link";

// Fontu yapılandır
const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // Farklı ağırlıkları kullanabilirsiniz
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        <Header />
        <Link/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
